name: usb_gadget
description: A Dart library for interfacing with Linux FunctionFs to create USB gadget functions. Supports USB device emulation on Linux systems with configfs.
version: 1.0.0

environment:
  sdk: ^3.10.0

dependencies:
  ffi: ^2.1.4
  meta: ^1.17.0

dev_dependencies:
  custom_lint: ^0.8.1
  ffigen: ^20.1.1
  leancode_lint: ^19.0.1
  lints: ^6.0.0
  args: any
  test: ^1.25.0
