name: usb_gadget
description: Expose standard or fully custom USB peripherals (gadgets) through a USB device controller (UDC) on Linux.
version: 0.1.0
homepage: https://github.com/GuillaumeMCK/usb-gadget

environment:
  sdk: ^3.10.0

dependencies:
  ffi: ^2.1.4
  meta: ^1.17.0

dev_dependencies:
  custom_lint: ^0.8.1
  ffigen: ^20.1.1
  leancode_lint: ^19.0.1
  lints: ^6.0.0
